/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as FlightsRouteImport } from './routes/flights'
import { Route as IstanbulRouteImport } from './routes/istanbul'
import { Route as MapRouteImport } from './routes/map'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as RomaniaRouteImport } from './routes/romania'
import { Route as TrainRouteImport } from './routes/train'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsRoute = FlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const IstanbulRoute = IstanbulRouteImport.update({
  id: '/istanbul',
  path: '/istanbul',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const RomaniaRoute = RomaniaRouteImport.update({
  id: '/romania',
  path: '/romania',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainRoute = TrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/budget': typeof BudgetRoute
  '/flights': typeof FlightsRoute
  '/istanbul': typeof IstanbulRoute
  '/map': typeof MapRoute
  '/plan': typeof PlanRoute
  '/romania': typeof RomaniaRoute
  '/train': typeof TrainRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/budget': typeof BudgetRoute
  '/flights': typeof FlightsRoute
  '/istanbul': typeof IstanbulRoute
  '/map': typeof MapRoute
  '/plan': typeof PlanRoute
  '/romania': typeof RomaniaRoute
  '/train': typeof TrainRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/budget': typeof BudgetRoute
  '/flights': typeof FlightsRoute
  '/istanbul': typeof IstanbulRoute
  '/map': typeof MapRoute
  '/plan': typeof PlanRoute
  '/romania': typeof RomaniaRoute
  '/train': typeof TrainRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agents'
    | '/budget'
    | '/flights'
    | '/istanbul'
    | '/map'
    | '/plan'
    | '/romania'
    | '/train'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agents'
    | '/budget'
    | '/flights'
    | '/istanbul'
    | '/map'
    | '/plan'
    | '/romania'
    | '/train'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agents'
    | '/budget'
    | '/flights'
    | '/istanbul'
    | '/map'
    | '/plan'
    | '/romania'
    | '/train'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgentsRoute: typeof AgentsRoute
  BudgetRoute: typeof BudgetRoute
  FlightsRoute: typeof FlightsRoute
  IstanbulRoute: typeof IstanbulRoute
  MapRoute: typeof MapRoute
  PlanRoute: typeof PlanRoute
  RomaniaRoute: typeof RomaniaRoute
  TrainRoute: typeof TrainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights': {
      id: '/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof FlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/istanbul': {
      id: '/istanbul'
      path: '/istanbul'
      fullPath: '/istanbul'
      preLoaderRoute: typeof IstanbulRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/romania': {
      id: '/romania'
      path: '/romania'
      fullPath: '/romania'
      preLoaderRoute: typeof RomaniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train': {
      id: '/train'
      path: '/train'
      fullPath: '/train'
      preLoaderRoute: typeof TrainRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgentsRoute: AgentsRoute,
  BudgetRoute: BudgetRoute,
  FlightsRoute: FlightsRoute,
  IstanbulRoute: IstanbulRoute,
  MapRoute: MapRoute,
  PlanRoute: PlanRoute,
  RomaniaRoute: RomaniaRoute,
  TrainRoute: TrainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
